### ISSUE TITLE
No matching distribution found for dataclasses; python_version < "3.7"

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim-wheels#10]
This happens during [windows builds](https://ci.appveyor.com/project/piskvorky/gensim-wheels-2x1bk/build/job/1dusrx9wak8c6o59).

```
pip install --pre --no-index --force-reinstall --find-links dist/ gensim
Looking in links: dist/
Processing c:\projects\gensim-wheels-2x1bk\gensim\dist\gensim-4.0.0b0-cp36-cp36m-win_amd64.whl
ERROR: Could not find a version that satisfies the requirement dataclasses; python_version < "3.7" (from gensim) (from versions: none)
ERROR: No matching distribution found for dataclasses; python_version < "3.7" (from gensim)
Command exited with code 1
ls -laht ../gensim/dist/
```

It's installing the gensim wheel it just built, and then failing to find the dataclasses backport. The build is happening under Py3.6.0, so dataclasses should be available via PyPI, but it's not.

**Comment by piskvorky** [comment]
I looked at `dataclasses ` and I found we use that dependency in a single place in the entire Gensim, here:

```python
@dataclass
class Doctag:
    """A dataclass shape-compatible with keyedvectors.SimpleVocab, extended to record
    details of string document tags discovered during the initial vocabulary scan.

    Will not be used if all presented document tags are ints. No longer used in a
    completed model: just used during initial scan, and for backward compatibility.
    """
```

According to [dataclasses docs](https://docs.python.org/3/library/dataclasses.html) the decorator just adds `__init__` (and `__repr__` and `__eq__`, which I don't think we care about) so it seems inessential and an overkill here. In the interest of finishing the release, I propose getting rid of it, at least until we drop py3.6 – `dataclasses` is built-in since py3.7.

@mpenkov I can help and remove the dep + add `__init__`. But let me know from where / to where to push the commit, to avoid making a mess of the release.

**Comment by mpenkov** [comment]
That won't help us finish the release, because we'll have to update the gensim repo and effectively repeat the release procedure.

**Comment by piskvorky** [comment]
OK.

**Comment by mpenkov** [comment]
Seems relevant: https://github.com/pypa/pip/issues/3254

Also: https://www.python.org/dev/peps/pep-0508/#environment-markers

**Comment by mpenkov** [comment]
Opened https://github.com/pypa/pip/issues/9134, let's see what they say.

Will try a workaround in the meantime.

**Comment by mpenkov** [comment]
As the pip guys pointed out to us, we were using a pip flag that prevented pip from discovering the packages that it needs.

I'm not sure how it ever worked in the past.
